#BSUB -n 20 -R 'select[nxt] rusage[mem=1024] span[ptile=20]' -M 1024
#BSUB -J Cholesky -o Cholesky.%J -L /bin/bash -W 3:00
##
##NECESSARY JOB SPECIFICATIONS
##BSUB -J JobName             # Set the job name to "JobName"
##BSUB -L /bin/bash           # Uses the bash login shell to initialize the job's execution environment.
##BSUB -W hh:mm               # Sets job's runtime wall-clock limit in hours:minutes or just minutes (-mm)
##BSUB -n NNN                 # NNN: total number of cores/jobslots to allocate for the job
##BSUB -R "select[node-type]" # Select node-type: nxt, mem256gb, gpu, phi, mem1t, mem2t ...
##BSUB -R "span[ptile=4]"    # XX:  number of cores/jobslots per node to use. Also, a node selection criterion.
##BSUB -R "rusage[mem=nnn]"   # Reserves nnn MBs per process/CPU for the job
##BSUB -M mm                  # Sets the per process enforceable memory limit to nnn MB
##BSUB -o HW1_part1.%J       # Send stdout and stderr to "OUTPUTFILE.[jobID]"
#
# <--- at this point the current working directory is the one you submitted the job from.
#
module load intel/2017A       # load Intel software stack

g++ -O3 -fopenmp -o Cholesky Cholesky.cpp

#
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 1000"
./Cholesky 1000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 2000"
./Cholesky 2000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 3000"
./Cholesky 3000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 4000"
./Cholesky 4000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 5000"
./Cholesky 5000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 6000"
./Cholesky 6000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 7000"
./Cholesky 7000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 8000"
./Cholesky 8000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 9000"
./Cholesky 9000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=1
echo "NUM_THREADS=1; Input Size = 10000"
./Cholesky 10000
echo "============================"

echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 1000"
./Cholesky 1000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 2000"
./Cholesky 2000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 3000"
./Cholesky 3000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 4000"
./Cholesky 4000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 5000"
./Cholesky 5000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 6000"
./Cholesky 6000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 7000"
./Cholesky 7000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 8000"
./Cholesky 8000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 9000"
./Cholesky 9000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=2
echo "NUM_THREADS=2; Input Size = 10000"
./Cholesky 10000
echo "============================"

echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 1000"
./Cholesky 1000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 2000"
./Cholesky 2000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 3000"
./Cholesky 3000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 4000"
./Cholesky 4000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 5000"
./Cholesky 5000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 6000"
./Cholesky 6000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 7000"
./Cholesky 7000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 8000"
./Cholesky 8000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 9000"
./Cholesky 9000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=4
echo "NUM_THREADS=4; Input Size = 10000"
./Cholesky 10000
echo "============================"

echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 1000"
./Cholesky 1000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 2000"
./Cholesky 2000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 3000"
./Cholesky 3000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 4000"
./Cholesky 4000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 5000"
./Cholesky 5000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 6000"
./Cholesky 6000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 7000"
./Cholesky 7000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 8000"
./Cholesky 8000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 9000"
./Cholesky 9000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=8
echo "NUM_THREADS=8; Input Size = 10000"
./Cholesky 10000
echo "============================"

echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 1000"
./Cholesky 1000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 2000"
./Cholesky 2000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 3000"
./Cholesky 3000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 4000"
./Cholesky 4000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 5000"
./Cholesky 5000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 6000"
./Cholesky 6000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 7000"
./Cholesky 7000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 8000"
./Cholesky 8000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 9000"
./Cholesky 9000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=16
echo "NUM_THREADS=16; Input Size = 10000"
./Cholesky 10000
echo "============================"

echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 1000"
./Cholesky 1000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 2000"
./Cholesky 2000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 3000"
./Cholesky 3000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 4000"
./Cholesky 4000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 5000"
./Cholesky 5000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 6000"
./Cholesky 6000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 7000"
./Cholesky 7000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 8000"
./Cholesky 8000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 9000"
./Cholesky 9000
echo "============================"
echo "============================"
export OMP_NUM_THREADS=20
echo "NUM_THREADS=20; Input Size = 10000"
./Cholesky 10000
echo "============================"
